import { Alert, Button, Tag, message } from "antd";
import { Eye, RefreshCw } from "lucide-react";
import { useEffect, useState } from "react";
import { PageHeader, Panel, PlatformBadge } from "../components/Shared";
import { controlApi } from "../services/controlApi";
import type { Platform } from "../types";

type Draft = { id: string; platform: Platform; accountId?: string; status: "draft" | "approved" | "submitting" | "succeeded" | "failed_retryable" | "unknown_requires_review"; errorCode?: string; createdAt?: string };
const statusMap: Record<Draft["status"], { label: string; color: string }> = { draft: { label: "草稿", color: "default" }, approved: { label: "已审批", color: "blue" }, submitting: { label: "提交中", color: "gold" }, succeeded: { label: "已发布", color: "green" }, failed_retryable: { label: "可重试失败", color: "red" }, unknown_requires_review: { label: "需要人工核查", color: "orange" } };
export function ReleasePage() { const [drafts, setDrafts] = useState<Draft[]>([]); const [messageApi, contextHolder] = message.useMessage(); const refresh = () => void controlApi.listPublicationDrafts().then((items) => setDrafts(items as Draft[])).catch((error: Error) => messageApi.error(error.message)); useEffect(refresh, [messageApi]); const act = (draft: Draft) => void (draft.status === "draft" ? controlApi.approvePublicationDraft(draft.id) : controlApi.executePublicationDraft(draft.id)).then(refresh).catch((error: Error) => messageApi.error(error.message)); return <>{contextHolder}<PageHeader title="发布执行" meta="只执行生成层确认的 PublicationDraft，并保留真实回执状态" actions={<Button icon={<RefreshCw size={15} />} onClick={refresh}>刷新状态</Button>} /><Alert className="section-alert" type="warning" showIcon message="Publisher 尚未配置时不会产生成功记录；执行结果会明确记录为失败或需要人工核查。" /><div className="release-layout"><Panel title="Publisher 执行队列" caption="PostgreSQL PublicationDraft"><div className="execution-list">{drafts.length === 0 ? <div className="empty-state">当前没有 PublicationDraft</div> : drafts.map((draft) => <div className="execution-row" key={draft.id}><div className="execution-primary"><div className="job-name">{draft.id}</div><div className="job-sub">{draft.createdAt || "—"}</div></div><div className="execution-fact"><span>平台</span><PlatformBadge platform={draft.platform} /></div><div className="execution-fact"><span>账号</span><strong>{draft.accountId || "未指定"}</strong></div><div className="execution-fact"><span>状态</span><Tag color={statusMap[draft.status].color}>{statusMap[draft.status].label}</Tag></div><div className="execution-fact"><span>错误</span><strong>{draft.errorCode || "—"}</strong></div><Button aria-label={`处理 ${draft.id}`} icon={<Eye size={14} />} disabled={draft.status !== "draft" && draft.status !== "approved"} onClick={() => act(draft)} /></div>)}</div></Panel><Panel title="执行边界" caption="Publisher Contract"><div className="summary-list"><div className="summary-row"><span className="muted">输入</span><strong>Approved Draft</strong></div><div className="summary-row"><span className="muted">平台 / 账号改写</span><strong>禁止</strong></div><div className="summary-divider" /><div className="job-sub">未配置 Provider 时，执行按钮只会写入明确失败状态，不会伪造外部帖子 ID。</div></div></Panel></div></>; }
