import { Alert, Button, Tag, message } from "antd";
import { RefreshCw, Send, ShieldCheck } from "lucide-react";
import { useEffect, useState } from "react";
import { PageHeader, Panel, PlatformBadge } from "../components/Shared";
import { controlApi } from "../services/controlApi";
import { useDemoState } from "../state/demoStateContext";
import type { Platform } from "../types";

type Draft = { id: string; platform: Platform; accountId?: string; status: "draft" | "approved" | "submitting" | "succeeded" | "failed_retryable" | "unknown_requires_review"; errorCode?: string; errorMessage?: string; createdAt?: string; contentDraftId?: string; revision?: { title?: string; sourceSnapshot?: { sourcePosts?: Array<{ canonicalUrl?: string }> } } };
const statusMap: Record<Draft["status"], { label: string; color: string }> = { draft: { label: "草稿", color: "default" }, approved: { label: "已审批", color: "blue" }, submitting: { label: "提交中", color: "gold" }, succeeded: { label: "已发布", color: "green" }, failed_retryable: { label: "可重试失败", color: "red" }, unknown_requires_review: { label: "需要人工核查", color: "orange" } };
export function ReleasePage() {
  const { selectedProject } = useDemoState();
  const [drafts, setDrafts] = useState<Draft[]>([]);
  const [messageApi, contextHolder] = message.useMessage();
  const refresh = () => void controlApi.listPublicationDrafts(selectedProject || undefined).then((items) => setDrafts(items as Draft[])).catch((error: Error) => messageApi.error(error.message));
  useEffect(() => { let active = true; setDrafts([]); if (selectedProject) void controlApi.listPublicationDrafts(selectedProject).then((items) => { if (active) setDrafts(items as Draft[]); }).catch((error: Error) => { if (active) messageApi.error(error.message); }); return () => { active = false; }; }, [messageApi, selectedProject]);
  const act = (draft: Draft) => void (draft.status === "draft" ? controlApi.approvePublicationDraft(selectedProject, draft.id) : controlApi.executePublicationDraft(selectedProject, draft.id)).then(refresh).catch((error: Error) => messageApi.error(error.message));
  return <>{contextHolder}<PageHeader title="发布队列" meta="只接收已通过人工审核的待审草稿，并保留来源、版本与真实回执" actions={<Button icon={<RefreshCw size={15} />} onClick={refresh}>刷新状态</Button>} /><Alert className="section-alert" type="warning" showIcon message="小红书 Publisher API 只有在配置真实回环服务后才会触碰手机；未配置时明确失败，绝不伪造成功。" /><div className="release-layout"><Panel title="发布执行队列" caption="PostgreSQL PublicationDraft"><div className="execution-list">{drafts.length === 0 ? <div className="empty-state">当前项目还没有发布任务</div> : drafts.map((draft) => <div className="execution-row" key={draft.id}><div className="execution-primary"><div className="job-name">{draft.revision?.title || `发布任务 ${draft.id.slice(0, 8)}`}</div><div className="job-sub">草稿 {draft.contentDraftId?.slice(0, 8) || "—"} · 来源 {draft.revision?.sourceSnapshot?.sourcePosts?.length || 0} 条 · {draft.createdAt || "—"}</div></div><div className="execution-fact"><span>平台</span><PlatformBadge platform={draft.platform} /></div><div className="execution-fact"><span>账号</span><strong>{draft.accountId?.slice(0, 8) || "未指定"}</strong></div><div className="execution-fact"><span>状态</span><Tag color={statusMap[draft.status].color}>{statusMap[draft.status].label}</Tag></div><div className="execution-fact"><span>结果</span><strong title={draft.errorMessage}>{draft.errorCode || "—"}</strong></div><Button disabled={draft.status !== "draft" && draft.status !== "approved" && draft.status !== "failed_retryable"} icon={draft.status === "draft" ? <ShieldCheck size={14} /> : <Send size={14} />} onClick={() => act(draft)}>{draft.status === "draft" ? "确认发布" : draft.status === "failed_retryable" ? "重试" : "执行"}</Button></div>)}</div></Panel><Panel title="执行边界" caption="Publisher Contract"><div className="summary-list"><div className="summary-row"><span className="muted">输入</span><strong>已批准 ContentDraft</strong></div><div className="summary-row"><span className="muted">账号范围</span><strong>当前项目 Publishing 绑定</strong></div><div className="summary-row"><span className="muted">平台 / 账号改写</span><strong>禁止</strong></div><div className="summary-divider" /><div className="job-sub">未配置 Publisher 时只记录明确失败；接入后必须保存外部帖子 ID、URL 与回执，未知结果进入人工核查且禁止自动重试。</div></div></Panel></div></>;
}
